language: r
cache: packages
sudo: required
dist: trusty

branches:
  only:
    - master
os: osx
osx_image: xcode9.3
r_packages:
  - devtools
  - pkgdown
  - units
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libgdal-dev
    - libproj-dev
    - libmagick++-dev
    - libudunits2-dev
  homebrew:
    packages:
    - libgit2
warnings_are_errors: false
latex: false
env:
  global:
  - NOT_CRAN=true
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

after_success:
  - Rscript -e "devtools::install_github('camille-s/camiller')"
  - Rscript -e "pkgdown::build_site(run_dont_run = TRUE)"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  local_dir: docs
  keep_history: true
