---
title: "colorbars"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(tidyverse)
library(crayon)
```

```{r}
yellows <- c("#FDCC8A", "#FC8D59", "#D7301F")
ptol <- ggthemes::ptol_pal()(12)
```



```{r}
color_prev <- function(colors, labels = T, label_color = "black", border = F, border_color = "white", border_size = 0.5) {
  p <- tibble(x = 1:length(colors), y = 0, fill = colors) %>%
    ggplot(aes(xmin = x, xmax = x + 1, ymin = y, ymax = y + 1, fill = fill)) +
      scale_fill_identity() +
      scale_color_identity() +
      theme_void()
  if (border) {
    p <- p + geom_rect(color = border_color, size = border_size)
  } else {
    p <- p + geom_rect()
  }
  if (labels) {
    p <- p + ggfittext::geom_fit_text(aes(label = fill), color = label_color)
  }
  p + 
    geom_text(aes(label = x, x = x + 0.5, y = y + 1, color = fill), fontface = "bold", vjust = 0.5, hjust = 0.5, nudge_y = 0.05)
}

color_prev(ptol, label_color = "gold", border = F)
```

```{r}
tol4 <- ptol[c(1, 3, 6, 9)]

combn(ptol, 2) %>%
  t() %>%
  as_tibble() %>%
  mutate(comb = paste(V1, V2, sep = " + ")) %>%
  gather(key = key, value = fill, -comb) %>%
  mutate(value = abs(runif(nrow(.), 1, 1.25))) %>%
  rowwise() %>%
  mutate(place = str_which(ptol, fixed(fill))) %>%
  ungroup() %>%
  group_by(comb) %>%
  mutate(row = row_number()) %>%
  ggplot(aes(x = comb, y = value, fill = fill)) +
    geom_col(position = "dodge", width = 0.7) +
    geom_text(aes(y = value * 0.95, label = place), color = "white", position = position_dodge(width = 0.7), fontface = "bold") +
    geom_text(aes(y = value * 0.85, label = place), color = "black", position = position_dodge(width = 0.7), fontface = "bold") +
    scale_fill_identity() +
    scale_x_discrete(expand = expand_scale(add = 0.6)) +
    theme_void() +
    theme(strip.text = element_text(face = "bold")) +
    facet_wrap(~ comb, scales = "free_x", ncol = length(ptol) - 1)
```


```{r}
ptol %>%
  walk(function(col) {
    value <- hex2RGB(col) %>% as("HSV") %>% coords() %>% as_tibble() %>% pull(V)
    text <- ifelse(value >= (2/3), "black", "white")
    text_style <- make_style(text)
    bg_style <- make_style(col, bg = T)
    cat(text_style(paste(col, "\t"), bg = bg_style))
  })
```



